name: Build Angular Project

on:
  push:
    branches:
      - master  # Triggers the workflow when code is pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version compatible with your project

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: npm run build -- --configuration production
